symfony/src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Label;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\ManyToMany(targetEntity=Annonce::class, mappedBy="categories")
     */
    private $annonces;

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->Label;
    }

    public function setLabel(string $Label): self
    {
        $this->Label = $Label;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection|Annonce[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->addCategory($this);
        }
        
        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            $annonce->removeCategory($this);
        }

        return $this;
    }
}

symfony/src/Controller/MembreController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Form\AnnonceType;
use App\Repository\AnnonceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

#[Route('/membre')]
class MembreController extends AbstractController
{


    #[Route('/create', name: 'membre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SluggerInterface $slugger): Response
    {
        $annonce = new Annonce();
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);
        $messageConfirmation = "";
        if ($form->isSubmitted() && $form->isValid()) {

            $annonce->setDatePublication(new \DateTime());
            $userconnecte = $this->getUser();
            $annonce->setUser($userconnecte);


            // code de gestion de upload image
            $imageFile = $form->get('image')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'imageFilename' property to store the PDF file name
                // instead of its contents
                $annonce->setImage($newFilename);
            } else {
                $annonce->setImage('');
            }




            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonce);
            $entityManager->flush();

            $messageConfirmation = "votre annonce est publiée";
        }

        return $this->render('membre/membre.html.twig', [
            'annonce' => $annonce,
            'form' => $form->createView(),
            'messageConfirmation' => $messageConfirmation ?? "",
        ]);
    }

    #[Route('/', name: 'membre_index', methods: ['GET'])]
    public function index(AnnonceRepository $annonceRepository): Response
    {
        $userConnecte = $this->getUser();
        return $this->render('membre/index.html.twig', [
            'controller_name' => 'MembreController',
            'annonces' => $annonceRepository->findby([
                "user" => $userConnecte
            ]),
        ]);
    }

    #[Route('/{id}', name: 'membre_show', methods: ['GET'])]
    public function show(Annonce $annonce): Response
    {
        return $this->render('annonce/show.html.twig', [
            'annonce' => $annonce,
        ]);
    }

    #[Route('/{id}', name: 'membre_delete', methods: ['DELETE'])]
    public function delete(Request $request, Annonce $annonce): Response
    {
        if ($this->isCsrfTokenValid('delete' . $annonce->getId(), $request->request->get('_token'))) {
            //verifier que l'anonce appartient a l 'utilisateur connecté 
            $userConnecte = $this->getUser();
            $auteurAnnonce = $annonce->getUser();
            if ($userConnecte != null && $auteurAnnonce != null) {
                if ($userConnecte->getid() == $auteurAnnonce->getid()) {
                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->remove($annonce);
                    $entityManager->flush();

                    // il faudrait aussi suprprimer le fichier image 

                    $dossierUpload = $this->getparameter('images_directory');
                    $fichierImage = "$dossierUpload/" . $annonce->getImage();
                    if (is_file($fichierImage)) {
                        unlink($fichierImage);
                    }
                }
            }
            //declenche le delete de la ligne

        }

        return $this->redirectToRoute('membre_index');
    }


    #[Route('/{id}/edit', name: 'membre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Annonce $annonce, SluggerInterface $slugger): Response
    {
        $userConnecte = $this->getUser();
        $auteurAnnonce = $annonce->getUser();
        if ($userConnecte != null && $auteurAnnonce != null) {
            if ($userConnecte->getid() == $auteurAnnonce->getid()) {

                $form = $this->createForm(AnnonceType::class, $annonce);
                $form->handleRequest($request);
                if ($form->isSubmitted() && $form->isValid()) {

                    // code de gestion de upload image
                    $imageFile = $form->get('image')->getData();

                    // this condition is needed because the 'brochure' field is not required
                    // so the PDF file must be processed only when a file is uploaded
                    if ($imageFile) {
                        $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                        // this is needed to safely include the file name as part of the URL
                        $safeFilename = $slugger->slug($originalFilename);
                        $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                        // Move the file to the directory where brochures are stored
                        try {

                            $imageFile->move(
                                $this->getParameter('images_directory'),
                                $newFilename
                            );
                        } catch (FileException $e) {
                            // ... handle exception if something happens during file upload
                        }
                        //supprimer l'image d'avant 

                        $dossierUpload = $this->getparameter('images_directory');
                        $fichierImage = "$dossierUpload/" . $annonce->getImage();
                        if (is_file($fichierImage)) {
                        unlink($fichierImage);
                        }
                        // updates the 'imageFilename' property to store the PDF file name
                        // instead of its contents
                        $annonce->setImage($newFilename);
                    } else {
                        $annonce->setImage('');
                    }
                    //la mise a jour est déclencée automatiquement 
                    //car symfony sait déja que l'objet $annonce est associée a une ligne SQL
                    $this->getDoctrine()->getManager()->flush();

                    return $this->redirectToRoute('membre_index');
                }

                return $this->render('membre/edit.html.twig', [
                    'annonce' => $annonce,
                    'form' => $form->createView(),
                ]);
            } else {
                return $this->redirectToRoute('membre_index');
            }
        } else {
            return $this->redirectToRoute('membre_index');
        }
    }
}

symfony/templates/membre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Annonce{% endblock %}

{% block body %}
    <h1>Edit Annonce</h1>


{{ form_start(form) }}

    {# {{ form_widget(form) }} #}
    {{form_row(form.titre) }}
    {{form_row(form.contenu) }}
    <img src="{{ asset('uploads/' ~ annonce.image) }}" class="img-fluid">
    {{form_row(form.image) }}
    {{form_row(form.slug) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}


    <a href="{{ path('membre_index') }}">back to list</a>

{% endblock %}

symfony/templates/membre/index.html.twig
{% extends 'membre.html.twig' %}

{% block title %}Hello MembreController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bonjour {{ app.user.username }}! 😁</h1>
    <p> bienvenue petit dans ton espace pour creer des annonce ;) </p>
    <a href="{{ path('membre_new') }}">Creer une annonce</a>


    <h2>liste de vos annonces</h2>
 <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>slug</th>
                <th>Titre</th>
                <th>categories</th>
                <th>Contenu</th>
                <th>Image</th>
                <th>DatePublication</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for annonce in app.user.annonces %}
            <tr>
                <td>{{ annonce.id }}</td>
                <td>{{ annonce.slug }}</td>
                <td>{{ annonce.titre }}</td>
                <td>
                {% if annonce.categories|length > 0 %}
                    {% for categorie in annonce.categories %}
                    <p>{{categorie.label}}</p>
                    {% endfor %}
                {% endif %}

                </td>
                <td>{{ annonce.contenu }}</td>
                {% if annonce.image %}
                <td><img src="{{ asset('uploads/' ~ annonce.image) }}" class="img-fluid"></td>
                {% else %}
                <td>pas d'images :'(</td>
                {% endif %}
                <td>{{ annonce.datePublication ? annonce.datePublication|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('membre_show', {'id': annonce.id}) }}">show</a>
                    <a href="{{ path('membre_edit', {'id': annonce.id}) }}">edit</a>
                <form method="post" action="{{ path('membre_delete', {'id': annonce.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ annonce.id) }}">
                <button class="btn btn-danger">Delete</button>
                </form>
                </td>
           
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

symfony/templates/membre/membre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace Membre{% endblock %}

{% block body %}
    <h1>espace membre</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Publier votre annonce') }}</button>
        <div>{{ messageConfirmation }}</div>
    {{ form_end(form) }}


{% endblock %}